name = "blog-likes"
account_id = "57e18b4fb317b217ebf8b0f74415ab9e"
compatibility_date = "2025-04-01"
main = "src/index.js"
workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "blog-likes"
database_id = "210d1bd9-ede1-4cf0-9697-028f48de81dd"

[observability.logs]
enabled = true


